#export impath="/home/---/Images/MRA-Dataset/"
export impath="/home/---/DataSets/148_TOFs_0.4_nii/"

python3 Artery_Classif.py -i ${impath}/0.nii -seg ${impath}/0.seg.nii -j ${impath}/0.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/1.nii -seg ${impath}/1.seg.nii -j ${impath}/1.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/10.nii -seg ${impath}/10.seg.nii -j ${impath}/10.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/100.nii -seg ${impath}/100.seg.nii -j ${impath}/100.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/101.nii -seg ${impath}/101.seg.nii -j ${impath}/101.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/102.nii -seg ${impath}/102.seg.nii -j ${impath}/102.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/103.nii -seg ${impath}/103.seg.nii -j ${impath}/103.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/104.nii -seg ${impath}/104.seg.nii -j ${impath}/104.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/105.nii -seg ${impath}/105.seg.nii -j ${impath}/105.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/106.nii -seg ${impath}/106.seg.nii -j ${impath}/106.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/107.nii -seg ${impath}/107.seg.nii -j ${impath}/107.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/108.nii -seg ${impath}/108.seg.nii -j ${impath}/108.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/109.nii -seg ${impath}/109.seg.nii -j ${impath}/109.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/11.nii -seg ${impath}/11.seg.nii -j ${impath}/11.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/110.nii -seg ${impath}/110.seg.nii -j ${impath}/110.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/111.nii -seg ${impath}/111.seg.nii -j ${impath}/111.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/112.nii -seg ${impath}/112.seg.nii -j ${impath}/112.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/113.nii -seg ${impath}/113.seg.nii -j ${impath}/113.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/114.nii -seg ${impath}/114.seg.nii -j ${impath}/114.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/115.nii -seg ${impath}/115.seg.nii -j ${impath}/115.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/116.nii -seg ${impath}/116.seg.nii -j ${impath}/116.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/117.nii -seg ${impath}/117.seg.nii -j ${impath}/117.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/118.nii -seg ${impath}/118.seg.nii -j ${impath}/118.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/119.nii -seg ${impath}/119.seg.nii -j ${impath}/119.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/12.nii -seg ${impath}/12.seg.nii -j ${impath}/12.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/120.nii -seg ${impath}/120.seg.nii -j ${impath}/120.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/121.nii -seg ${impath}/121.seg.nii -j ${impath}/121.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/122.nii -seg ${impath}/122.seg.nii -j ${impath}/122.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/123.nii -seg ${impath}/123.seg.nii -j ${impath}/123.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/124.nii -seg ${impath}/124.seg.nii -j ${impath}/124.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/125.nii -seg ${impath}/125.seg.nii -j ${impath}/125.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/126.nii -seg ${impath}/126.seg.nii -j ${impath}/126.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/127.nii -seg ${impath}/127.seg.nii -j ${impath}/127.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/128.nii -seg ${impath}/128.seg.nii -j ${impath}/128.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/129.nii -seg ${impath}/129.seg.nii -j ${impath}/129.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/13.nii -seg ${impath}/13.seg.nii -j ${impath}/13.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/130.nii -seg ${impath}/130.seg.nii -j ${impath}/130.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/131.nii -seg ${impath}/131.seg.nii -j ${impath}/131.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/132.nii -seg ${impath}/132.seg.nii -j ${impath}/132.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/133.nii -seg ${impath}/133.seg.nii -j ${impath}/133.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/134.nii -seg ${impath}/134.seg.nii -j ${impath}/134.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/135.nii -seg ${impath}/135.seg.nii -j ${impath}/135.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/136.nii -seg ${impath}/136.seg.nii -j ${impath}/136.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/137.nii -seg ${impath}/137.seg.nii -j ${impath}/137.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/138.nii -seg ${impath}/138.seg.nii -j ${impath}/138.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/139.nii -seg ${impath}/139.seg.nii -j ${impath}/139.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/14.nii -seg ${impath}/14.seg.nii -j ${impath}/14.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/140.nii -seg ${impath}/140.seg.nii -j ${impath}/140.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/141.nii -seg ${impath}/141.seg.nii -j ${impath}/141.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/142.nii -seg ${impath}/142.seg.nii -j ${impath}/142.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/143.nii -seg ${impath}/143.seg.nii -j ${impath}/143.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/144.nii -seg ${impath}/144.seg.nii -j ${impath}/144.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/145.nii -seg ${impath}/145.seg.nii -j ${impath}/145.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/146.nii -seg ${impath}/146.seg.nii -j ${impath}/146.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/147.nii -seg ${impath}/147.seg.nii -j ${impath}/147.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/149.nii -seg ${impath}/149.seg.nii -j ${impath}/149.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/15.nii -seg ${impath}/15.seg.nii -j ${impath}/15.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/150.nii -seg ${impath}/150.seg.nii -j ${impath}/150.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/151.nii -seg ${impath}/151.seg.nii -j ${impath}/151.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/152.nii -seg ${impath}/152.seg.nii -j ${impath}/152.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/153.nii -seg ${impath}/153.seg.nii -j ${impath}/153.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/154.nii -seg ${impath}/154.seg.nii -j ${impath}/154.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/155.nii -seg ${impath}/155.seg.nii -j ${impath}/155.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/156.nii -seg ${impath}/156.seg.nii -j ${impath}/156.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/158.nii -seg ${impath}/158.seg.nii -j ${impath}/158.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/159.nii -seg ${impath}/159.seg.nii -j ${impath}/159.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/16.nii -seg ${impath}/16.seg.nii -j ${impath}/16.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/160.nii -seg ${impath}/160.seg.nii -j ${impath}/160.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/161.nii -seg ${impath}/161.seg.nii -j ${impath}/161.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/162.nii -seg ${impath}/162.seg.nii -j ${impath}/162.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/163.nii -seg ${impath}/163.seg.nii -j ${impath}/163.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/164.nii -seg ${impath}/164.seg.nii -j ${impath}/164.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/165.nii -seg ${impath}/165.seg.nii -j ${impath}/165.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/166.nii -seg ${impath}/166.seg.nii -j ${impath}/166.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/167.nii -seg ${impath}/167.seg.nii -j ${impath}/167.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/169.nii -seg ${impath}/169.seg.nii -j ${impath}/169.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/17.nii -seg ${impath}/17.seg.nii -j ${impath}/17.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/170.nii -seg ${impath}/170.seg.nii -j ${impath}/170.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/171.nii -seg ${impath}/171.seg.nii -j ${impath}/171.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/172.nii -seg ${impath}/172.seg.nii -j ${impath}/172.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/174.nii -seg ${impath}/174.seg.nii -j ${impath}/174.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/18.nii -seg ${impath}/18.seg.nii -j ${impath}/18.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/19.nii -seg ${impath}/19.seg.nii -j ${impath}/19.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/20.nii -seg ${impath}/20.seg.nii -j ${impath}/20.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/21.nii -seg ${impath}/21.seg.nii -j ${impath}/21.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/22.nii -seg ${impath}/22.seg.nii -j ${impath}/22.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/23.nii -seg ${impath}/23.seg.nii -j ${impath}/23.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/24.nii -seg ${impath}/24.seg.nii -j ${impath}/24.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/25.nii -seg ${impath}/25.seg.nii -j ${impath}/25.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/26.nii -seg ${impath}/26.seg.nii -j ${impath}/26.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/27.nii -seg ${impath}/27.seg.nii -j ${impath}/27.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/28.nii -seg ${impath}/28.seg.nii -j ${impath}/28.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/29.nii -seg ${impath}/29.seg.nii -j ${impath}/29.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/3.nii -seg ${impath}/3.seg.nii -j ${impath}/3.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/30.nii -seg ${impath}/30.seg.nii -j ${impath}/30.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/31.nii -seg ${impath}/31.seg.nii -j ${impath}/31.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/32.nii -seg ${impath}/32.seg.nii -j ${impath}/32.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/33.nii -seg ${impath}/33.seg.nii -j ${impath}/33.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/35.nii -seg ${impath}/35.seg.nii -j ${impath}/35.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/36.nii -seg ${impath}/36.seg.nii -j ${impath}/36.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/37.nii -seg ${impath}/37.seg.nii -j ${impath}/37.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/38.nii -seg ${impath}/38.seg.nii -j ${impath}/38.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/39.nii -seg ${impath}/39.seg.nii -j ${impath}/39.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/4.nii -seg ${impath}/4.seg.nii -j ${impath}/4.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/40.nii -seg ${impath}/40.seg.nii -j ${impath}/40.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/41.nii -seg ${impath}/41.seg.nii -j ${impath}/41.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/42.nii -seg ${impath}/42.seg.nii -j ${impath}/42.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/43.nii -seg ${impath}/43.seg.nii -j ${impath}/43.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/45.nii -seg ${impath}/45.seg.nii -j ${impath}/45.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/46.nii -seg ${impath}/46.seg.nii -j ${impath}/46.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/47.nii -seg ${impath}/47.seg.nii -j ${impath}/47.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/48.nii -seg ${impath}/48.seg.nii -j ${impath}/48.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/49.nii -seg ${impath}/49.seg.nii -j ${impath}/49.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/5.nii -seg ${impath}/5.seg.nii -j ${impath}/5.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/53.nii -seg ${impath}/53.seg.nii -j ${impath}/53.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/55.nii -seg ${impath}/55.seg.nii -j ${impath}/55.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/56.nii -seg ${impath}/56.seg.nii -j ${impath}/56.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/57.nii -seg ${impath}/57.seg.nii -j ${impath}/57.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/58.nii -seg ${impath}/58.seg.nii -j ${impath}/58.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/59.nii -seg ${impath}/59.seg.nii -j ${impath}/59.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/6.nii -seg ${impath}/6.seg.nii -j ${impath}/6.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/60.nii -seg ${impath}/60.seg.nii -j ${impath}/60.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/61.nii -seg ${impath}/61.seg.nii -j ${impath}/61.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/62.nii -seg ${impath}/62.seg.nii -j ${impath}/62.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/63.nii -seg ${impath}/63.seg.nii -j ${impath}/63.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/64.nii -seg ${impath}/64.seg.nii -j ${impath}/64.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/65.nii -seg ${impath}/65.seg.nii -j ${impath}/65.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/66.nii -seg ${impath}/66.seg.nii -j ${impath}/66.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/67.nii -seg ${impath}/67.seg.nii -j ${impath}/67.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/69.nii -seg ${impath}/69.seg.nii -j ${impath}/69.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/7.nii -seg ${impath}/7.seg.nii -j ${impath}/7.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/70.nii -seg ${impath}/70.seg.nii -j ${impath}/70.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/71.nii -seg ${impath}/71.seg.nii -j ${impath}/71.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/73.nii -seg ${impath}/73.seg.nii -j ${impath}/73.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/74.nii -seg ${impath}/74.seg.nii -j ${impath}/74.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/76.nii -seg ${impath}/76.seg.nii -j ${impath}/76.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/77.nii -seg ${impath}/77.seg.nii -j ${impath}/77.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/79.nii -seg ${impath}/79.seg.nii -j ${impath}/79.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/8.nii -seg ${impath}/8.seg.nii -j ${impath}/8.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/80.nii -seg ${impath}/80.seg.nii -j ${impath}/80.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/81.nii -seg ${impath}/81.seg.nii -j ${impath}/81.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/82.nii -seg ${impath}/82.seg.nii -j ${impath}/82.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/83.nii -seg ${impath}/83.seg.nii -j ${impath}/83.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/85.nii -seg ${impath}/85.seg.nii -j ${impath}/85.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/86.nii -seg ${impath}/86.seg.nii -j ${impath}/86.seg_F.mrk.json
python3 Artery_Classif.py -i ${impath}/9.nii -seg ${impath}/9.seg.nii -j ${impath}/9.seg_F.mrk.json
