python thin_art.py /home/---/Images/MRA-Dataset/0_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/100_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/101_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/102_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/103_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/104_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/105_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/106_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/107_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/109_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/10_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/110_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/111_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/112_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/113_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/114_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/115_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/116_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/117_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/118_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/119_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/11_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/120_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/121_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/122_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/123_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/124_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/125_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/126_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/127_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/128_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/129_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/12_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/130_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/131_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/132_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/133_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/134_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/135_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/136_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/137_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/138_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/139_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/13_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/140_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/141_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/142_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/143_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/144_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/145_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/146_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/149_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/14_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/150_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/151_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/152_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/153_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/154_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/155_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/156_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/158_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/159_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/15_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/160_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/161_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/162_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/163_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/164_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/165_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/166_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/167_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/169_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/16_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/170_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/171_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/172_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/174_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/17_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/18_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/19_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/1_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/20_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/21_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/22_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/23_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/24_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/25_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/26_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/27_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/28_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/29_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/30_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/31_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/32_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/33_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/35_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/36_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/37_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/38_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/39_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/3_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/40_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/41_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/42_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/43_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/45_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/46_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/47_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/48_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/49_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/4_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/53_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/55_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/56_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/57_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/58_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/59_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/5_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/60_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/61_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/62_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/63_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/64_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/65_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/66_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/67_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/69_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/6_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/70_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/71_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/73_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/74_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/76_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/77_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/79_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/7_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/80_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/81_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/82_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/83_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/85_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/86_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/8_labels.seg.nrrd
python thin_art.py /home/---/Images/MRA-Dataset/9_labels.seg.nrrd
